version: '3.7'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cluster-information
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: root@123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

  infinispan:
    image: quay.io/infinispan/server:14.0
    environment:
      USER: admin
      PASS: password
    ports:
      - "11222:11222"
    volumes:
      - ./infinispan.xml:/opt/infinispan/server/conf/infinispan.xml
      - ./org.keycloak.keycloak-model-infinispan-21.0.2.jar:/opt/infinispan/server/lib/org.keycloak.keycloak-model-infinispan-21.0.2.jar
      - ./org.keycloak.keycloak-common-21.0.2.jar:/opt/infinispan/server/lib/org.keycloak.keycloak-common-21.0.2.jar
      - ./org.keycloak.keycloak-core-21.0.2.jar:/opt/infinispan/server/lib/org.keycloak.keycloak-core-21.0.2.jar
      - ./org.keycloak.keycloak-server-spi-21.0.2.jar:/opt/infinispan/server/lib/org.keycloak.keycloak-server-spi-21.0.2.jar
      - ./org.keycloak.keycloak-server-spi-private-21.0.2.jar:/opt/infinispan/server/lib/org.keycloak.keycloak-server-spi-private-21.0.2.jar
      - ./org.keycloak.keycloak-services-21.0.2.jar:/opt/infinispan/server/lib/org.keycloak.keycloak-services-21.0.2.jar
      - ./mysql-connector-j-8.0.31.jar:/opt/infinispan/boot/mysql-connector-j-8.0.31.jar
    networks:
      - mynetwork

  keycloak:
    image: keycloak/keycloak:21.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # KEYCLOAK_HOSTNAME: myapp.com
      # KC_HOSTNAME: myapp.com
      KC_HOSTNAME: localhost
      PROXY_ADDRESS_FORWARDING: "true"
    ports:
      - "8081:8080"
      - "8443:8443"
    depends_on:
      - infinispan
    volumes:
      - ./cache-ispn.xml:/opt/keycloak/conf/cache-ispn.xml
      - ./keycloak.conf:/opt/keycloak/conf/keycloak.conf
      - ./keycloak.crt:/opt/keycloak/conf/keycloak.crt
      - ./keycloak.key:/opt/keycloak/conf/keycloak.key
      - ./hosts:/etc/hosts
      # - ./server.keystore:/opt/keycloak/conf/server.keystore

    networks:
      - mynetwork

    entrypoint: ["/opt/keycloak/bin/kc.sh","start"]


volumes:
  infinispan-data:
  mysql-data:

networks:
  mynetwork:
    driver: bridge    



